// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: opencraft.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Messages from clients to servers
type ToServer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//
	//	*ToServer_IWantPlayer
	//	*ToServer_IWantMovePlayer
	//	*ToServer_IWantChangeBlock
	//	*ToServer_IWantColumn
	Payload isToServer_Payload `protobuf_oneof:"payload"`
}

func (x *ToServer) Reset() {
	*x = ToServer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_opencraft_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ToServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToServer) ProtoMessage() {}

func (x *ToServer) ProtoReflect() protoreflect.Message {
	mi := &file_opencraft_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToServer.ProtoReflect.Descriptor instead.
func (*ToServer) Descriptor() ([]byte, []int) {
	return file_opencraft_proto_rawDescGZIP(), []int{0}
}

func (m *ToServer) GetPayload() isToServer_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *ToServer) GetIWantPlayer() *IWantPlayer {
	if x, ok := x.GetPayload().(*ToServer_IWantPlayer); ok {
		return x.IWantPlayer
	}
	return nil
}

func (x *ToServer) GetIWantMovePlayer() *IWantMovePlayer {
	if x, ok := x.GetPayload().(*ToServer_IWantMovePlayer); ok {
		return x.IWantMovePlayer
	}
	return nil
}

func (x *ToServer) GetIWantChangeBlock() *IWantChangeBlock {
	if x, ok := x.GetPayload().(*ToServer_IWantChangeBlock); ok {
		return x.IWantChangeBlock
	}
	return nil
}

func (x *ToServer) GetIWantColumn() *IWantColumn {
	if x, ok := x.GetPayload().(*ToServer_IWantColumn); ok {
		return x.IWantColumn
	}
	return nil
}

type isToServer_Payload interface {
	isToServer_Payload()
}

type ToServer_IWantPlayer struct {
	IWantPlayer *IWantPlayer `protobuf:"bytes,1,opt,name=i_want_player,json=iWantPlayer,proto3,oneof"`
}

type ToServer_IWantMovePlayer struct {
	IWantMovePlayer *IWantMovePlayer `protobuf:"bytes,2,opt,name=i_want_move_player,json=iWantMovePlayer,proto3,oneof"`
}

type ToServer_IWantChangeBlock struct {
	IWantChangeBlock *IWantChangeBlock `protobuf:"bytes,3,opt,name=i_want_change_block,json=iWantChangeBlock,proto3,oneof"`
}

type ToServer_IWantColumn struct {
	IWantColumn *IWantColumn `protobuf:"bytes,4,opt,name=i_want_column,json=iWantColumn,proto3,oneof"`
}

func (*ToServer_IWantPlayer) isToServer_Payload() {}

func (*ToServer_IWantMovePlayer) isToServer_Payload() {}

func (*ToServer_IWantChangeBlock) isToServer_Payload() {}

func (*ToServer_IWantColumn) isToServer_Payload() {}

type IWantPlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerID uint32 `protobuf:"varint,1,opt,name=playerID,proto3" json:"playerID,omitempty"`
}

func (x *IWantPlayer) Reset() {
	*x = IWantPlayer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_opencraft_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IWantPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IWantPlayer) ProtoMessage() {}

func (x *IWantPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_opencraft_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IWantPlayer.ProtoReflect.Descriptor instead.
func (*IWantPlayer) Descriptor() ([]byte, []int) {
	return file_opencraft_proto_rawDescGZIP(), []int{1}
}

func (x *IWantPlayer) GetPlayerID() uint32 {
	if x != nil {
		return x.PlayerID
	}
	return 0
}

type IWantMovePlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerID    uint32 `protobuf:"varint,1,opt,name=playerID,proto3" json:"playerID,omitempty"`
	NewPosition *Vec3  `protobuf:"bytes,2,opt,name=newPosition,proto3" json:"newPosition,omitempty"`
}

func (x *IWantMovePlayer) Reset() {
	*x = IWantMovePlayer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_opencraft_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IWantMovePlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IWantMovePlayer) ProtoMessage() {}

func (x *IWantMovePlayer) ProtoReflect() protoreflect.Message {
	mi := &file_opencraft_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IWantMovePlayer.ProtoReflect.Descriptor instead.
func (*IWantMovePlayer) Descriptor() ([]byte, []int) {
	return file_opencraft_proto_rawDescGZIP(), []int{2}
}

func (x *IWantMovePlayer) GetPlayerID() uint32 {
	if x != nil {
		return x.PlayerID
	}
	return 0
}

func (x *IWantMovePlayer) GetNewPosition() *Vec3 {
	if x != nil {
		return x.NewPosition
	}
	return nil
}

type IWantChangeBlock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockPosition *Pos3  `protobuf:"bytes,1,opt,name=blockPosition,proto3" json:"blockPosition,omitempty"`
	BlockType     uint32 `protobuf:"varint,2,opt,name=blockType,proto3" json:"blockType,omitempty"`
}

func (x *IWantChangeBlock) Reset() {
	*x = IWantChangeBlock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_opencraft_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IWantChangeBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IWantChangeBlock) ProtoMessage() {}

func (x *IWantChangeBlock) ProtoReflect() protoreflect.Message {
	mi := &file_opencraft_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IWantChangeBlock.ProtoReflect.Descriptor instead.
func (*IWantChangeBlock) Descriptor() ([]byte, []int) {
	return file_opencraft_proto_rawDescGZIP(), []int{3}
}

func (x *IWantChangeBlock) GetBlockPosition() *Pos3 {
	if x != nil {
		return x.BlockPosition
	}
	return nil
}

func (x *IWantChangeBlock) GetBlockType() uint32 {
	if x != nil {
		return x.BlockType
	}
	return 0
}

type IWantColumn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ColumnPos *Pos2 `protobuf:"bytes,1,opt,name=columnPos,proto3" json:"columnPos,omitempty"`
}

func (x *IWantColumn) Reset() {
	*x = IWantColumn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_opencraft_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IWantColumn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IWantColumn) ProtoMessage() {}

func (x *IWantColumn) ProtoReflect() protoreflect.Message {
	mi := &file_opencraft_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IWantColumn.ProtoReflect.Descriptor instead.
func (*IWantColumn) Descriptor() ([]byte, []int) {
	return file_opencraft_proto_rawDescGZIP(), []int{4}
}

func (x *IWantColumn) GetColumnPos() *Pos2 {
	if x != nil {
		return x.ColumnPos
	}
	return nil
}

// Messages from servers to clients
type ToClient struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//
	//	*ToClient_YouArePlayer
	//	*ToClient_PlayerUpdate
	//	*ToClient_ChunkData
	//	*ToClient_ColumnData
	//	*ToClient_BlockUpdate
	//	*ToClient_MultiBlockUpdate
	Payload isToClient_Payload `protobuf_oneof:"payload"`
}

func (x *ToClient) Reset() {
	*x = ToClient{}
	if protoimpl.UnsafeEnabled {
		mi := &file_opencraft_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ToClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToClient) ProtoMessage() {}

func (x *ToClient) ProtoReflect() protoreflect.Message {
	mi := &file_opencraft_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToClient.ProtoReflect.Descriptor instead.
func (*ToClient) Descriptor() ([]byte, []int) {
	return file_opencraft_proto_rawDescGZIP(), []int{5}
}

func (m *ToClient) GetPayload() isToClient_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *ToClient) GetYouArePlayer() *YouArePlayer {
	if x, ok := x.GetPayload().(*ToClient_YouArePlayer); ok {
		return x.YouArePlayer
	}
	return nil
}

func (x *ToClient) GetPlayerUpdate() *PlayerUpdate {
	if x, ok := x.GetPayload().(*ToClient_PlayerUpdate); ok {
		return x.PlayerUpdate
	}
	return nil
}

func (x *ToClient) GetChunkData() *ChunkData {
	if x, ok := x.GetPayload().(*ToClient_ChunkData); ok {
		return x.ChunkData
	}
	return nil
}

func (x *ToClient) GetColumnData() *ColumnData {
	if x, ok := x.GetPayload().(*ToClient_ColumnData); ok {
		return x.ColumnData
	}
	return nil
}

func (x *ToClient) GetBlockUpdate() *BlockUpdate {
	if x, ok := x.GetPayload().(*ToClient_BlockUpdate); ok {
		return x.BlockUpdate
	}
	return nil
}

func (x *ToClient) GetMultiBlockUpdate() *MultiBlockUpdate {
	if x, ok := x.GetPayload().(*ToClient_MultiBlockUpdate); ok {
		return x.MultiBlockUpdate
	}
	return nil
}

type isToClient_Payload interface {
	isToClient_Payload()
}

type ToClient_YouArePlayer struct {
	YouArePlayer *YouArePlayer `protobuf:"bytes,1,opt,name=you_are_player,json=youArePlayer,proto3,oneof"`
}

type ToClient_PlayerUpdate struct {
	PlayerUpdate *PlayerUpdate `protobuf:"bytes,2,opt,name=player_update,json=playerUpdate,proto3,oneof"`
}

type ToClient_ChunkData struct {
	ChunkData *ChunkData `protobuf:"bytes,3,opt,name=chunk_data,json=chunkData,proto3,oneof"`
}

type ToClient_ColumnData struct {
	ColumnData *ColumnData `protobuf:"bytes,4,opt,name=column_data,json=columnData,proto3,oneof"`
}

type ToClient_BlockUpdate struct {
	BlockUpdate *BlockUpdate `protobuf:"bytes,5,opt,name=block_update,json=blockUpdate,proto3,oneof"`
}

type ToClient_MultiBlockUpdate struct {
	MultiBlockUpdate *MultiBlockUpdate `protobuf:"bytes,6,opt,name=multi_block_update,json=multiBlockUpdate,proto3,oneof"`
}

func (*ToClient_YouArePlayer) isToClient_Payload() {}

func (*ToClient_PlayerUpdate) isToClient_Payload() {}

func (*ToClient_ChunkData) isToClient_Payload() {}

func (*ToClient_ColumnData) isToClient_Payload() {}

func (*ToClient_BlockUpdate) isToClient_Payload() {}

func (*ToClient_MultiBlockUpdate) isToClient_Payload() {}

type YouArePlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerID      uint32 `protobuf:"varint,1,opt,name=playerID,proto3" json:"playerID,omitempty"`
	SpawnLocation *Vec3  `protobuf:"bytes,2,opt,name=spawnLocation,proto3" json:"spawnLocation,omitempty"`
}

func (x *YouArePlayer) Reset() {
	*x = YouArePlayer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_opencraft_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *YouArePlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YouArePlayer) ProtoMessage() {}

func (x *YouArePlayer) ProtoReflect() protoreflect.Message {
	mi := &file_opencraft_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YouArePlayer.ProtoReflect.Descriptor instead.
func (*YouArePlayer) Descriptor() ([]byte, []int) {
	return file_opencraft_proto_rawDescGZIP(), []int{6}
}

func (x *YouArePlayer) GetPlayerID() uint32 {
	if x != nil {
		return x.PlayerID
	}
	return 0
}

func (x *YouArePlayer) GetSpawnLocation() *Vec3 {
	if x != nil {
		return x.SpawnLocation
	}
	return nil
}

type Vec3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float32 `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z float32 `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
}

func (x *Vec3) Reset() {
	*x = Vec3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_opencraft_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vec3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vec3) ProtoMessage() {}

func (x *Vec3) ProtoReflect() protoreflect.Message {
	mi := &file_opencraft_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vec3.ProtoReflect.Descriptor instead.
func (*Vec3) Descriptor() ([]byte, []int) {
	return file_opencraft_proto_rawDescGZIP(), []int{7}
}

func (x *Vec3) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vec3) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Vec3) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

type Pos2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X int32 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Z int32 `protobuf:"varint,2,opt,name=z,proto3" json:"z,omitempty"`
}

func (x *Pos2) Reset() {
	*x = Pos2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_opencraft_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pos2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pos2) ProtoMessage() {}

func (x *Pos2) ProtoReflect() protoreflect.Message {
	mi := &file_opencraft_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pos2.ProtoReflect.Descriptor instead.
func (*Pos2) Descriptor() ([]byte, []int) {
	return file_opencraft_proto_rawDescGZIP(), []int{8}
}

func (x *Pos2) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Pos2) GetZ() int32 {
	if x != nil {
		return x.Z
	}
	return 0
}

type Pos3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X int32 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y int32 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Z int32 `protobuf:"varint,3,opt,name=z,proto3" json:"z,omitempty"`
}

func (x *Pos3) Reset() {
	*x = Pos3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_opencraft_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pos3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pos3) ProtoMessage() {}

func (x *Pos3) ProtoReflect() protoreflect.Message {
	mi := &file_opencraft_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pos3.ProtoReflect.Descriptor instead.
func (*Pos3) Descriptor() ([]byte, []int) {
	return file_opencraft_proto_rawDescGZIP(), []int{9}
}

func (x *Pos3) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Pos3) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Pos3) GetZ() int32 {
	if x != nil {
		return x.Z
	}
	return 0
}

type PlayerUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerID uint32 `protobuf:"varint,1,opt,name=playerID,proto3" json:"playerID,omitempty"`
	Position *Vec3  `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
}

func (x *PlayerUpdate) Reset() {
	*x = PlayerUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_opencraft_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerUpdate) ProtoMessage() {}

func (x *PlayerUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_opencraft_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerUpdate.ProtoReflect.Descriptor instead.
func (*PlayerUpdate) Descriptor() ([]byte, []int) {
	return file_opencraft_proto_rawDescGZIP(), []int{10}
}

func (x *PlayerUpdate) GetPlayerID() uint32 {
	if x != nil {
		return x.PlayerID
	}
	return 0
}

func (x *PlayerUpdate) GetPosition() *Vec3 {
	if x != nil {
		return x.Position
	}
	return nil
}

type ChunkData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockTypes []byte `protobuf:"bytes,1,opt,name=blockTypes,proto3" json:"blockTypes,omitempty"`
}

func (x *ChunkData) Reset() {
	*x = ChunkData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_opencraft_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChunkData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkData) ProtoMessage() {}

func (x *ChunkData) ProtoReflect() protoreflect.Message {
	mi := &file_opencraft_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkData.ProtoReflect.Descriptor instead.
func (*ChunkData) Descriptor() ([]byte, []int) {
	return file_opencraft_proto_rawDescGZIP(), []int{11}
}

func (x *ChunkData) GetBlockTypes() []byte {
	if x != nil {
		return x.BlockTypes
	}
	return nil
}

type ColumnData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Position *Pos2        `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	Chunks   []*ChunkData `protobuf:"bytes,2,rep,name=chunks,proto3" json:"chunks,omitempty"`
}

func (x *ColumnData) Reset() {
	*x = ColumnData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_opencraft_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ColumnData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnData) ProtoMessage() {}

func (x *ColumnData) ProtoReflect() protoreflect.Message {
	mi := &file_opencraft_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnData.ProtoReflect.Descriptor instead.
func (*ColumnData) Descriptor() ([]byte, []int) {
	return file_opencraft_proto_rawDescGZIP(), []int{12}
}

func (x *ColumnData) GetPosition() *Pos2 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *ColumnData) GetChunks() []*ChunkData {
	if x != nil {
		return x.Chunks
	}
	return nil
}

type BlockUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockPosition *Pos3  `protobuf:"bytes,1,opt,name=blockPosition,proto3" json:"blockPosition,omitempty"`
	BlockType     uint32 `protobuf:"varint,2,opt,name=blockType,proto3" json:"blockType,omitempty"`
}

func (x *BlockUpdate) Reset() {
	*x = BlockUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_opencraft_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockUpdate) ProtoMessage() {}

func (x *BlockUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_opencraft_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockUpdate.ProtoReflect.Descriptor instead.
func (*BlockUpdate) Descriptor() ([]byte, []int) {
	return file_opencraft_proto_rawDescGZIP(), []int{13}
}

func (x *BlockUpdate) GetBlockPosition() *Pos3 {
	if x != nil {
		return x.BlockPosition
	}
	return nil
}

func (x *BlockUpdate) GetBlockType() uint32 {
	if x != nil {
		return x.BlockType
	}
	return 0
}

type MultiBlockUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Updates []*BlockUpdate `protobuf:"bytes,1,rep,name=updates,proto3" json:"updates,omitempty"`
}

func (x *MultiBlockUpdate) Reset() {
	*x = MultiBlockUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_opencraft_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiBlockUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiBlockUpdate) ProtoMessage() {}

func (x *MultiBlockUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_opencraft_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiBlockUpdate.ProtoReflect.Descriptor instead.
func (*MultiBlockUpdate) Descriptor() ([]byte, []int) {
	return file_opencraft_proto_rawDescGZIP(), []int{14}
}

func (x *MultiBlockUpdate) GetUpdates() []*BlockUpdate {
	if x != nil {
		return x.Updates
	}
	return nil
}

var File_opencraft_proto protoreflect.FileDescriptor

var file_opencraft_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x72, 0x61, 0x66, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x72, 0x61, 0x66, 0x74, 0x22, 0xaa, 0x02, 0x0a,
	0x08, 0x54, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x3c, 0x0a, 0x0d, 0x69, 0x5f, 0x77,
	0x61, 0x6e, 0x74, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x72, 0x61, 0x66, 0x74, 0x2e, 0x49, 0x57, 0x61,
	0x6e, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x48, 0x00, 0x52, 0x0b, 0x69, 0x57, 0x61, 0x6e,
	0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x49, 0x0a, 0x12, 0x69, 0x5f, 0x77, 0x61, 0x6e,
	0x74, 0x5f, 0x6d, 0x6f, 0x76, 0x65, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x72, 0x61, 0x66, 0x74, 0x2e,
	0x49, 0x57, 0x61, 0x6e, 0x74, 0x4d, 0x6f, 0x76, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x48,
	0x00, 0x52, 0x0f, 0x69, 0x57, 0x61, 0x6e, 0x74, 0x4d, 0x6f, 0x76, 0x65, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x12, 0x4c, 0x0a, 0x13, 0x69, 0x5f, 0x77, 0x61, 0x6e, 0x74, 0x5f, 0x63, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1b, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x72, 0x61, 0x66, 0x74, 0x2e, 0x49, 0x57, 0x61, 0x6e,
	0x74, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x00, 0x52, 0x10,
	0x69, 0x57, 0x61, 0x6e, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x12, 0x3c, 0x0a, 0x0d, 0x69, 0x5f, 0x77, 0x61, 0x6e, 0x74, 0x5f, 0x63, 0x6f, 0x6c, 0x75, 0x6d,
	0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x72,
	0x61, 0x66, 0x74, 0x2e, 0x49, 0x57, 0x61, 0x6e, 0x74, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x48,
	0x00, 0x52, 0x0b, 0x69, 0x57, 0x61, 0x6e, 0x74, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x42, 0x09,
	0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x29, 0x0a, 0x0b, 0x49, 0x57, 0x61,
	0x6e, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x49, 0x44, 0x22, 0x60, 0x0a, 0x0f, 0x49, 0x57, 0x61, 0x6e, 0x74, 0x4d, 0x6f, 0x76,
	0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x49, 0x44, 0x12, 0x31, 0x0a, 0x0b, 0x6e, 0x65, 0x77, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x63,
	0x72, 0x61, 0x66, 0x74, 0x2e, 0x56, 0x65, 0x63, 0x33, 0x52, 0x0b, 0x6e, 0x65, 0x77, 0x50, 0x6f,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x67, 0x0a, 0x10, 0x49, 0x57, 0x61, 0x6e, 0x74, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x35, 0x0a, 0x0d, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x72, 0x61, 0x66, 0x74, 0x2e, 0x50, 0x6f,
	0x73, 0x33, 0x52, 0x0d, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x22,
	0x3c, 0x0a, 0x0b, 0x49, 0x57, 0x61, 0x6e, 0x74, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x12, 0x2d,
	0x0a, 0x09, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x50, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x72, 0x61, 0x66, 0x74, 0x2e, 0x50, 0x6f,
	0x73, 0x32, 0x52, 0x09, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x50, 0x6f, 0x73, 0x22, 0x91, 0x03,
	0x0a, 0x08, 0x54, 0x6f, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x3f, 0x0a, 0x0e, 0x79, 0x6f,
	0x75, 0x5f, 0x61, 0x72, 0x65, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x72, 0x61, 0x66, 0x74, 0x2e, 0x59,
	0x6f, 0x75, 0x41, 0x72, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x48, 0x00, 0x52, 0x0c, 0x79,
	0x6f, 0x75, 0x41, 0x72, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x3e, 0x0a, 0x0d, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x72, 0x61, 0x66, 0x74, 0x2e, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x00, 0x52, 0x0c, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x35, 0x0a, 0x0a, 0x63,
	0x68, 0x75, 0x6e, 0x6b, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x72, 0x61, 0x66, 0x74, 0x2e, 0x43, 0x68, 0x75, 0x6e,
	0x6b, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x09, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x38, 0x0a, 0x0b, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x5f, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x72,
	0x61, 0x66, 0x74, 0x2e, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00,
	0x52, 0x0a, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x12, 0x3b, 0x0a, 0x0c,
	0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x72, 0x61, 0x66, 0x74, 0x2e, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x00, 0x52, 0x0b, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x4b, 0x0a, 0x12, 0x6d, 0x75, 0x6c,
	0x74, 0x69, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x72, 0x61, 0x66,
	0x74, 0x2e, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x48, 0x00, 0x52, 0x10, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x22, 0x61, 0x0a, 0x0c, 0x59, 0x6f, 0x75, 0x41, 0x72, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x12, 0x35, 0x0a,
	0x0d, 0x73, 0x70, 0x61, 0x77, 0x6e, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x72, 0x61, 0x66, 0x74,
	0x2e, 0x56, 0x65, 0x63, 0x33, 0x52, 0x0d, 0x73, 0x70, 0x61, 0x77, 0x6e, 0x4c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x30, 0x0a, 0x04, 0x56, 0x65, 0x63, 0x33, 0x12, 0x0c, 0x0a, 0x01,
	0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x79, 0x12, 0x0c, 0x0a, 0x01, 0x7a, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x01, 0x7a, 0x22, 0x22, 0x0a, 0x04, 0x50, 0x6f, 0x73, 0x32, 0x12, 0x0c,
	0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01,
	0x7a, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x7a, 0x22, 0x30, 0x0a, 0x04, 0x50, 0x6f,
	0x73, 0x33, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x78,
	0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x79, 0x12, 0x0c,
	0x0a, 0x01, 0x7a, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x7a, 0x22, 0x57, 0x0a, 0x0c,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x12, 0x2b, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6f, 0x70, 0x65,
	0x6e, 0x63, 0x72, 0x61, 0x66, 0x74, 0x2e, 0x56, 0x65, 0x63, 0x33, 0x52, 0x08, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2b, 0x0a, 0x09, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x54, 0x79, 0x70,
	0x65, 0x73, 0x22, 0x67, 0x0a, 0x0a, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x2b, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x72, 0x61, 0x66, 0x74, 0x2e, 0x50,
	0x6f, 0x73, 0x32, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2c, 0x0a,
	0x06, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x6f, 0x70, 0x65, 0x6e, 0x63, 0x72, 0x61, 0x66, 0x74, 0x2e, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x06, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x22, 0x62, 0x0a, 0x0b, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x35, 0x0a, 0x0d, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x72, 0x61, 0x66, 0x74, 0x2e, 0x50, 0x6f,
	0x73, 0x33, 0x52, 0x0d, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x22,
	0x44, 0x0a, 0x10, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x12, 0x30, 0x0a, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x72, 0x61, 0x66, 0x74,
	0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x07, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x73, 0x42, 0x1e, 0x5a, 0x08, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0xaa, 0x02, 0x11, 0x4f, 0x70, 0x65, 0x6e, 0x63, 0x72, 0x61, 0x66, 0x74, 0x2e, 0x4e, 0x65,
	0x74, 0x43, 0x6f, 0x64, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_opencraft_proto_rawDescOnce sync.Once
	file_opencraft_proto_rawDescData = file_opencraft_proto_rawDesc
)

func file_opencraft_proto_rawDescGZIP() []byte {
	file_opencraft_proto_rawDescOnce.Do(func() {
		file_opencraft_proto_rawDescData = protoimpl.X.CompressGZIP(file_opencraft_proto_rawDescData)
	})
	return file_opencraft_proto_rawDescData
}

var file_opencraft_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_opencraft_proto_goTypes = []any{
	(*ToServer)(nil),         // 0: opencraft.ToServer
	(*IWantPlayer)(nil),      // 1: opencraft.IWantPlayer
	(*IWantMovePlayer)(nil),  // 2: opencraft.IWantMovePlayer
	(*IWantChangeBlock)(nil), // 3: opencraft.IWantChangeBlock
	(*IWantColumn)(nil),      // 4: opencraft.IWantColumn
	(*ToClient)(nil),         // 5: opencraft.ToClient
	(*YouArePlayer)(nil),     // 6: opencraft.YouArePlayer
	(*Vec3)(nil),             // 7: opencraft.Vec3
	(*Pos2)(nil),             // 8: opencraft.Pos2
	(*Pos3)(nil),             // 9: opencraft.Pos3
	(*PlayerUpdate)(nil),     // 10: opencraft.PlayerUpdate
	(*ChunkData)(nil),        // 11: opencraft.ChunkData
	(*ColumnData)(nil),       // 12: opencraft.ColumnData
	(*BlockUpdate)(nil),      // 13: opencraft.BlockUpdate
	(*MultiBlockUpdate)(nil), // 14: opencraft.MultiBlockUpdate
}
var file_opencraft_proto_depIdxs = []int32{
	1,  // 0: opencraft.ToServer.i_want_player:type_name -> opencraft.IWantPlayer
	2,  // 1: opencraft.ToServer.i_want_move_player:type_name -> opencraft.IWantMovePlayer
	3,  // 2: opencraft.ToServer.i_want_change_block:type_name -> opencraft.IWantChangeBlock
	4,  // 3: opencraft.ToServer.i_want_column:type_name -> opencraft.IWantColumn
	7,  // 4: opencraft.IWantMovePlayer.newPosition:type_name -> opencraft.Vec3
	9,  // 5: opencraft.IWantChangeBlock.blockPosition:type_name -> opencraft.Pos3
	8,  // 6: opencraft.IWantColumn.columnPos:type_name -> opencraft.Pos2
	6,  // 7: opencraft.ToClient.you_are_player:type_name -> opencraft.YouArePlayer
	10, // 8: opencraft.ToClient.player_update:type_name -> opencraft.PlayerUpdate
	11, // 9: opencraft.ToClient.chunk_data:type_name -> opencraft.ChunkData
	12, // 10: opencraft.ToClient.column_data:type_name -> opencraft.ColumnData
	13, // 11: opencraft.ToClient.block_update:type_name -> opencraft.BlockUpdate
	14, // 12: opencraft.ToClient.multi_block_update:type_name -> opencraft.MultiBlockUpdate
	7,  // 13: opencraft.YouArePlayer.spawnLocation:type_name -> opencraft.Vec3
	7,  // 14: opencraft.PlayerUpdate.position:type_name -> opencraft.Vec3
	8,  // 15: opencraft.ColumnData.position:type_name -> opencraft.Pos2
	11, // 16: opencraft.ColumnData.chunks:type_name -> opencraft.ChunkData
	9,  // 17: opencraft.BlockUpdate.blockPosition:type_name -> opencraft.Pos3
	13, // 18: opencraft.MultiBlockUpdate.updates:type_name -> opencraft.BlockUpdate
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_opencraft_proto_init() }
func file_opencraft_proto_init() {
	if File_opencraft_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_opencraft_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ToServer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_opencraft_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*IWantPlayer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_opencraft_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*IWantMovePlayer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_opencraft_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*IWantChangeBlock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_opencraft_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*IWantColumn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_opencraft_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*ToClient); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_opencraft_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*YouArePlayer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_opencraft_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*Vec3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_opencraft_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*Pos2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_opencraft_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*Pos3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_opencraft_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*PlayerUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_opencraft_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*ChunkData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_opencraft_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*ColumnData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_opencraft_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*BlockUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_opencraft_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*MultiBlockUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_opencraft_proto_msgTypes[0].OneofWrappers = []any{
		(*ToServer_IWantPlayer)(nil),
		(*ToServer_IWantMovePlayer)(nil),
		(*ToServer_IWantChangeBlock)(nil),
		(*ToServer_IWantColumn)(nil),
	}
	file_opencraft_proto_msgTypes[5].OneofWrappers = []any{
		(*ToClient_YouArePlayer)(nil),
		(*ToClient_PlayerUpdate)(nil),
		(*ToClient_ChunkData)(nil),
		(*ToClient_ColumnData)(nil),
		(*ToClient_BlockUpdate)(nil),
		(*ToClient_MultiBlockUpdate)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_opencraft_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_opencraft_proto_goTypes,
		DependencyIndexes: file_opencraft_proto_depIdxs,
		MessageInfos:      file_opencraft_proto_msgTypes,
	}.Build()
	File_opencraft_proto = out.File
	file_opencraft_proto_rawDesc = nil
	file_opencraft_proto_goTypes = nil
	file_opencraft_proto_depIdxs = nil
}
