// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: opencraft.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Opencraft.NetCode {

  /// <summary>Holder for reflection information generated from opencraft.proto</summary>
  public static partial class OpencraftReflection {

    #region Descriptor
    /// <summary>File descriptor for opencraft.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static OpencraftReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9vcGVuY3JhZnQucHJvdG8SCW9wZW5jcmFmdCLtAQoIVG9TZXJ2ZXISLwoN",
            "aV93YW50X3BsYXllchgBIAEoCzIWLm9wZW5jcmFmdC5JV2FudFBsYXllckgA",
            "EjgKEmlfd2FudF9tb3ZlX3BsYXllchgCIAEoCzIaLm9wZW5jcmFmdC5JV2Fu",
            "dE1vdmVQbGF5ZXJIABI6ChNpX3dhbnRfY2hhbmdlX2Jsb2NrGAMgASgLMhsu",
            "b3BlbmNyYWZ0LklXYW50Q2hhbmdlQmxvY2tIABIvCg1pX3dhbnRfY29sdW1u",
            "GAQgASgLMhYub3BlbmNyYWZ0LklXYW50Q29sdW1uSABCCQoHcGF5bG9hZCIf",
            "CgtJV2FudFBsYXllchIQCghwbGF5ZXJJRBgBIAEoDSJJCg9JV2FudE1vdmVQ",
            "bGF5ZXISEAoIcGxheWVySUQYASABKA0SJAoLbmV3UG9zaXRpb24YAiABKAsy",
            "Dy5vcGVuY3JhZnQuVmVjMyJNChBJV2FudENoYW5nZUJsb2NrEiYKDWJsb2Nr",
            "UG9zaXRpb24YASABKAsyDy5vcGVuY3JhZnQuUG9zMxIRCglibG9ja1R5cGUY",
            "AiABKA0iMQoLSVdhbnRDb2x1bW4SIgoJY29sdW1uUG9zGAEgASgLMg8ub3Bl",
            "bmNyYWZ0LlBvczIivwIKCFRvQ2xpZW50EjEKDnlvdV9hcmVfcGxheWVyGAEg",
            "ASgLMhcub3BlbmNyYWZ0LllvdUFyZVBsYXllckgAEjAKDXBsYXllcl91cGRh",
            "dGUYAiABKAsyFy5vcGVuY3JhZnQuUGxheWVyVXBkYXRlSAASKgoKY2h1bmtf",
            "ZGF0YRgDIAEoCzIULm9wZW5jcmFmdC5DaHVua0RhdGFIABIsCgtjb2x1bW5f",
            "ZGF0YRgEIAEoCzIVLm9wZW5jcmFmdC5Db2x1bW5EYXRhSAASLgoMYmxvY2tf",
            "dXBkYXRlGAUgASgLMhYub3BlbmNyYWZ0LkJsb2NrVXBkYXRlSAASOQoSbXVs",
            "dGlfYmxvY2tfdXBkYXRlGAYgASgLMhsub3BlbmNyYWZ0Lk11bHRpQmxvY2tV",
            "cGRhdGVIAEIJCgdwYXlsb2FkIkgKDFlvdUFyZVBsYXllchIQCghwbGF5ZXJJ",
            "RBgBIAEoDRImCg1zcGF3bkxvY2F0aW9uGAIgASgLMg8ub3BlbmNyYWZ0LlZl",
            "YzMiJwoEVmVjMxIJCgF4GAEgASgCEgkKAXkYAiABKAISCQoBehgDIAEoAiIc",
            "CgRQb3MyEgkKAXgYASABKBESCQoBehgCIAEoESInCgRQb3MzEgkKAXgYASAB",
            "KBESCQoBeRgCIAEoERIJCgF6GAMgASgRIkMKDFBsYXllclVwZGF0ZRIQCghw",
            "bGF5ZXJJRBgBIAEoDRIhCghwb3NpdGlvbhgCIAEoCzIPLm9wZW5jcmFmdC5W",
            "ZWMzIh8KCUNodW5rRGF0YRISCgpibG9ja1R5cGVzGAEgASgMIlUKCkNvbHVt",
            "bkRhdGESIQoIcG9zaXRpb24YASABKAsyDy5vcGVuY3JhZnQuUG9zMhIkCgZj",
            "aHVua3MYAiADKAsyFC5vcGVuY3JhZnQuQ2h1bmtEYXRhIkgKC0Jsb2NrVXBk",
            "YXRlEiYKDWJsb2NrUG9zaXRpb24YASABKAsyDy5vcGVuY3JhZnQuUG9zMxIR",
            "CglibG9ja1R5cGUYAiABKA0iOwoQTXVsdGlCbG9ja1VwZGF0ZRInCgd1cGRh",
            "dGVzGAEgAygLMhYub3BlbmNyYWZ0LkJsb2NrVXBkYXRlQh5aCC4vcHJvdG9z",
            "qgIRT3BlbmNyYWZ0Lk5ldENvZGViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Opencraft.NetCode.ToServer), global::Opencraft.NetCode.ToServer.Parser, new[]{ "IWantPlayer", "IWantMovePlayer", "IWantChangeBlock", "IWantColumn" }, new[]{ "Payload" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Opencraft.NetCode.IWantPlayer), global::Opencraft.NetCode.IWantPlayer.Parser, new[]{ "PlayerID" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Opencraft.NetCode.IWantMovePlayer), global::Opencraft.NetCode.IWantMovePlayer.Parser, new[]{ "PlayerID", "NewPosition" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Opencraft.NetCode.IWantChangeBlock), global::Opencraft.NetCode.IWantChangeBlock.Parser, new[]{ "BlockPosition", "BlockType" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Opencraft.NetCode.IWantColumn), global::Opencraft.NetCode.IWantColumn.Parser, new[]{ "ColumnPos" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Opencraft.NetCode.ToClient), global::Opencraft.NetCode.ToClient.Parser, new[]{ "YouArePlayer", "PlayerUpdate", "ChunkData", "ColumnData", "BlockUpdate", "MultiBlockUpdate" }, new[]{ "Payload" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Opencraft.NetCode.YouArePlayer), global::Opencraft.NetCode.YouArePlayer.Parser, new[]{ "PlayerID", "SpawnLocation" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Opencraft.NetCode.Vec3), global::Opencraft.NetCode.Vec3.Parser, new[]{ "X", "Y", "Z" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Opencraft.NetCode.Pos2), global::Opencraft.NetCode.Pos2.Parser, new[]{ "X", "Z" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Opencraft.NetCode.Pos3), global::Opencraft.NetCode.Pos3.Parser, new[]{ "X", "Y", "Z" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Opencraft.NetCode.PlayerUpdate), global::Opencraft.NetCode.PlayerUpdate.Parser, new[]{ "PlayerID", "Position" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Opencraft.NetCode.ChunkData), global::Opencraft.NetCode.ChunkData.Parser, new[]{ "BlockTypes" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Opencraft.NetCode.ColumnData), global::Opencraft.NetCode.ColumnData.Parser, new[]{ "Position", "Chunks" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Opencraft.NetCode.BlockUpdate), global::Opencraft.NetCode.BlockUpdate.Parser, new[]{ "BlockPosition", "BlockType" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Opencraft.NetCode.MultiBlockUpdate), global::Opencraft.NetCode.MultiBlockUpdate.Parser, new[]{ "Updates" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Messages from clients to servers
  /// </summary>
  public sealed partial class ToServer : pb::IMessage<ToServer> {
    private static readonly pb::MessageParser<ToServer> _parser = new pb::MessageParser<ToServer>(() => new ToServer());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ToServer> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Opencraft.NetCode.OpencraftReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ToServer() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ToServer(ToServer other) : this() {
      switch (other.PayloadCase) {
        case PayloadOneofCase.IWantPlayer:
          IWantPlayer = other.IWantPlayer.Clone();
          break;
        case PayloadOneofCase.IWantMovePlayer:
          IWantMovePlayer = other.IWantMovePlayer.Clone();
          break;
        case PayloadOneofCase.IWantChangeBlock:
          IWantChangeBlock = other.IWantChangeBlock.Clone();
          break;
        case PayloadOneofCase.IWantColumn:
          IWantColumn = other.IWantColumn.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ToServer Clone() {
      return new ToServer(this);
    }

    /// <summary>Field number for the "i_want_player" field.</summary>
    public const int IWantPlayerFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Opencraft.NetCode.IWantPlayer IWantPlayer {
      get { return payloadCase_ == PayloadOneofCase.IWantPlayer ? (global::Opencraft.NetCode.IWantPlayer) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.IWantPlayer;
      }
    }

    /// <summary>Field number for the "i_want_move_player" field.</summary>
    public const int IWantMovePlayerFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Opencraft.NetCode.IWantMovePlayer IWantMovePlayer {
      get { return payloadCase_ == PayloadOneofCase.IWantMovePlayer ? (global::Opencraft.NetCode.IWantMovePlayer) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.IWantMovePlayer;
      }
    }

    /// <summary>Field number for the "i_want_change_block" field.</summary>
    public const int IWantChangeBlockFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Opencraft.NetCode.IWantChangeBlock IWantChangeBlock {
      get { return payloadCase_ == PayloadOneofCase.IWantChangeBlock ? (global::Opencraft.NetCode.IWantChangeBlock) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.IWantChangeBlock;
      }
    }

    /// <summary>Field number for the "i_want_column" field.</summary>
    public const int IWantColumnFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Opencraft.NetCode.IWantColumn IWantColumn {
      get { return payloadCase_ == PayloadOneofCase.IWantColumn ? (global::Opencraft.NetCode.IWantColumn) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.IWantColumn;
      }
    }

    private object payload_;
    /// <summary>Enum of possible cases for the "payload" oneof.</summary>
    public enum PayloadOneofCase {
      None = 0,
      IWantPlayer = 1,
      IWantMovePlayer = 2,
      IWantChangeBlock = 3,
      IWantColumn = 4,
    }
    private PayloadOneofCase payloadCase_ = PayloadOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PayloadOneofCase PayloadCase {
      get { return payloadCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearPayload() {
      payloadCase_ = PayloadOneofCase.None;
      payload_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ToServer);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ToServer other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(IWantPlayer, other.IWantPlayer)) return false;
      if (!object.Equals(IWantMovePlayer, other.IWantMovePlayer)) return false;
      if (!object.Equals(IWantChangeBlock, other.IWantChangeBlock)) return false;
      if (!object.Equals(IWantColumn, other.IWantColumn)) return false;
      if (PayloadCase != other.PayloadCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (payloadCase_ == PayloadOneofCase.IWantPlayer) hash ^= IWantPlayer.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.IWantMovePlayer) hash ^= IWantMovePlayer.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.IWantChangeBlock) hash ^= IWantChangeBlock.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.IWantColumn) hash ^= IWantColumn.GetHashCode();
      hash ^= (int) payloadCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (payloadCase_ == PayloadOneofCase.IWantPlayer) {
        output.WriteRawTag(10);
        output.WriteMessage(IWantPlayer);
      }
      if (payloadCase_ == PayloadOneofCase.IWantMovePlayer) {
        output.WriteRawTag(18);
        output.WriteMessage(IWantMovePlayer);
      }
      if (payloadCase_ == PayloadOneofCase.IWantChangeBlock) {
        output.WriteRawTag(26);
        output.WriteMessage(IWantChangeBlock);
      }
      if (payloadCase_ == PayloadOneofCase.IWantColumn) {
        output.WriteRawTag(34);
        output.WriteMessage(IWantColumn);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (payloadCase_ == PayloadOneofCase.IWantPlayer) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(IWantPlayer);
      }
      if (payloadCase_ == PayloadOneofCase.IWantMovePlayer) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(IWantMovePlayer);
      }
      if (payloadCase_ == PayloadOneofCase.IWantChangeBlock) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(IWantChangeBlock);
      }
      if (payloadCase_ == PayloadOneofCase.IWantColumn) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(IWantColumn);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ToServer other) {
      if (other == null) {
        return;
      }
      switch (other.PayloadCase) {
        case PayloadOneofCase.IWantPlayer:
          if (IWantPlayer == null) {
            IWantPlayer = new global::Opencraft.NetCode.IWantPlayer();
          }
          IWantPlayer.MergeFrom(other.IWantPlayer);
          break;
        case PayloadOneofCase.IWantMovePlayer:
          if (IWantMovePlayer == null) {
            IWantMovePlayer = new global::Opencraft.NetCode.IWantMovePlayer();
          }
          IWantMovePlayer.MergeFrom(other.IWantMovePlayer);
          break;
        case PayloadOneofCase.IWantChangeBlock:
          if (IWantChangeBlock == null) {
            IWantChangeBlock = new global::Opencraft.NetCode.IWantChangeBlock();
          }
          IWantChangeBlock.MergeFrom(other.IWantChangeBlock);
          break;
        case PayloadOneofCase.IWantColumn:
          if (IWantColumn == null) {
            IWantColumn = new global::Opencraft.NetCode.IWantColumn();
          }
          IWantColumn.MergeFrom(other.IWantColumn);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::Opencraft.NetCode.IWantPlayer subBuilder = new global::Opencraft.NetCode.IWantPlayer();
            if (payloadCase_ == PayloadOneofCase.IWantPlayer) {
              subBuilder.MergeFrom(IWantPlayer);
            }
            input.ReadMessage(subBuilder);
            IWantPlayer = subBuilder;
            break;
          }
          case 18: {
            global::Opencraft.NetCode.IWantMovePlayer subBuilder = new global::Opencraft.NetCode.IWantMovePlayer();
            if (payloadCase_ == PayloadOneofCase.IWantMovePlayer) {
              subBuilder.MergeFrom(IWantMovePlayer);
            }
            input.ReadMessage(subBuilder);
            IWantMovePlayer = subBuilder;
            break;
          }
          case 26: {
            global::Opencraft.NetCode.IWantChangeBlock subBuilder = new global::Opencraft.NetCode.IWantChangeBlock();
            if (payloadCase_ == PayloadOneofCase.IWantChangeBlock) {
              subBuilder.MergeFrom(IWantChangeBlock);
            }
            input.ReadMessage(subBuilder);
            IWantChangeBlock = subBuilder;
            break;
          }
          case 34: {
            global::Opencraft.NetCode.IWantColumn subBuilder = new global::Opencraft.NetCode.IWantColumn();
            if (payloadCase_ == PayloadOneofCase.IWantColumn) {
              subBuilder.MergeFrom(IWantColumn);
            }
            input.ReadMessage(subBuilder);
            IWantColumn = subBuilder;
            break;
          }
        }
      }
    }

  }

  public sealed partial class IWantPlayer : pb::IMessage<IWantPlayer> {
    private static readonly pb::MessageParser<IWantPlayer> _parser = new pb::MessageParser<IWantPlayer>(() => new IWantPlayer());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<IWantPlayer> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Opencraft.NetCode.OpencraftReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public IWantPlayer() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public IWantPlayer(IWantPlayer other) : this() {
      playerID_ = other.playerID_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public IWantPlayer Clone() {
      return new IWantPlayer(this);
    }

    /// <summary>Field number for the "playerID" field.</summary>
    public const int PlayerIDFieldNumber = 1;
    private uint playerID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint PlayerID {
      get { return playerID_; }
      set {
        playerID_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as IWantPlayer);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(IWantPlayer other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PlayerID != other.PlayerID) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (PlayerID != 0) hash ^= PlayerID.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (PlayerID != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(PlayerID);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (PlayerID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PlayerID);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(IWantPlayer other) {
      if (other == null) {
        return;
      }
      if (other.PlayerID != 0) {
        PlayerID = other.PlayerID;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            PlayerID = input.ReadUInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class IWantMovePlayer : pb::IMessage<IWantMovePlayer> {
    private static readonly pb::MessageParser<IWantMovePlayer> _parser = new pb::MessageParser<IWantMovePlayer>(() => new IWantMovePlayer());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<IWantMovePlayer> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Opencraft.NetCode.OpencraftReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public IWantMovePlayer() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public IWantMovePlayer(IWantMovePlayer other) : this() {
      playerID_ = other.playerID_;
      newPosition_ = other.newPosition_ != null ? other.newPosition_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public IWantMovePlayer Clone() {
      return new IWantMovePlayer(this);
    }

    /// <summary>Field number for the "playerID" field.</summary>
    public const int PlayerIDFieldNumber = 1;
    private uint playerID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint PlayerID {
      get { return playerID_; }
      set {
        playerID_ = value;
      }
    }

    /// <summary>Field number for the "newPosition" field.</summary>
    public const int NewPositionFieldNumber = 2;
    private global::Opencraft.NetCode.Vec3 newPosition_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Opencraft.NetCode.Vec3 NewPosition {
      get { return newPosition_; }
      set {
        newPosition_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as IWantMovePlayer);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(IWantMovePlayer other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PlayerID != other.PlayerID) return false;
      if (!object.Equals(NewPosition, other.NewPosition)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (PlayerID != 0) hash ^= PlayerID.GetHashCode();
      if (newPosition_ != null) hash ^= NewPosition.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (PlayerID != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(PlayerID);
      }
      if (newPosition_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(NewPosition);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (PlayerID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PlayerID);
      }
      if (newPosition_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(NewPosition);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(IWantMovePlayer other) {
      if (other == null) {
        return;
      }
      if (other.PlayerID != 0) {
        PlayerID = other.PlayerID;
      }
      if (other.newPosition_ != null) {
        if (newPosition_ == null) {
          NewPosition = new global::Opencraft.NetCode.Vec3();
        }
        NewPosition.MergeFrom(other.NewPosition);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            PlayerID = input.ReadUInt32();
            break;
          }
          case 18: {
            if (newPosition_ == null) {
              NewPosition = new global::Opencraft.NetCode.Vec3();
            }
            input.ReadMessage(NewPosition);
            break;
          }
        }
      }
    }

  }

  public sealed partial class IWantChangeBlock : pb::IMessage<IWantChangeBlock> {
    private static readonly pb::MessageParser<IWantChangeBlock> _parser = new pb::MessageParser<IWantChangeBlock>(() => new IWantChangeBlock());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<IWantChangeBlock> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Opencraft.NetCode.OpencraftReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public IWantChangeBlock() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public IWantChangeBlock(IWantChangeBlock other) : this() {
      blockPosition_ = other.blockPosition_ != null ? other.blockPosition_.Clone() : null;
      blockType_ = other.blockType_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public IWantChangeBlock Clone() {
      return new IWantChangeBlock(this);
    }

    /// <summary>Field number for the "blockPosition" field.</summary>
    public const int BlockPositionFieldNumber = 1;
    private global::Opencraft.NetCode.Pos3 blockPosition_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Opencraft.NetCode.Pos3 BlockPosition {
      get { return blockPosition_; }
      set {
        blockPosition_ = value;
      }
    }

    /// <summary>Field number for the "blockType" field.</summary>
    public const int BlockTypeFieldNumber = 2;
    private uint blockType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint BlockType {
      get { return blockType_; }
      set {
        blockType_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as IWantChangeBlock);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(IWantChangeBlock other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(BlockPosition, other.BlockPosition)) return false;
      if (BlockType != other.BlockType) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (blockPosition_ != null) hash ^= BlockPosition.GetHashCode();
      if (BlockType != 0) hash ^= BlockType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (blockPosition_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(BlockPosition);
      }
      if (BlockType != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(BlockType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (blockPosition_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BlockPosition);
      }
      if (BlockType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(BlockType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(IWantChangeBlock other) {
      if (other == null) {
        return;
      }
      if (other.blockPosition_ != null) {
        if (blockPosition_ == null) {
          BlockPosition = new global::Opencraft.NetCode.Pos3();
        }
        BlockPosition.MergeFrom(other.BlockPosition);
      }
      if (other.BlockType != 0) {
        BlockType = other.BlockType;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (blockPosition_ == null) {
              BlockPosition = new global::Opencraft.NetCode.Pos3();
            }
            input.ReadMessage(BlockPosition);
            break;
          }
          case 16: {
            BlockType = input.ReadUInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class IWantColumn : pb::IMessage<IWantColumn> {
    private static readonly pb::MessageParser<IWantColumn> _parser = new pb::MessageParser<IWantColumn>(() => new IWantColumn());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<IWantColumn> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Opencraft.NetCode.OpencraftReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public IWantColumn() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public IWantColumn(IWantColumn other) : this() {
      columnPos_ = other.columnPos_ != null ? other.columnPos_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public IWantColumn Clone() {
      return new IWantColumn(this);
    }

    /// <summary>Field number for the "columnPos" field.</summary>
    public const int ColumnPosFieldNumber = 1;
    private global::Opencraft.NetCode.Pos2 columnPos_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Opencraft.NetCode.Pos2 ColumnPos {
      get { return columnPos_; }
      set {
        columnPos_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as IWantColumn);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(IWantColumn other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(ColumnPos, other.ColumnPos)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (columnPos_ != null) hash ^= ColumnPos.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (columnPos_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ColumnPos);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (columnPos_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ColumnPos);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(IWantColumn other) {
      if (other == null) {
        return;
      }
      if (other.columnPos_ != null) {
        if (columnPos_ == null) {
          ColumnPos = new global::Opencraft.NetCode.Pos2();
        }
        ColumnPos.MergeFrom(other.ColumnPos);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (columnPos_ == null) {
              ColumnPos = new global::Opencraft.NetCode.Pos2();
            }
            input.ReadMessage(ColumnPos);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// Messages from servers to clients
  /// </summary>
  public sealed partial class ToClient : pb::IMessage<ToClient> {
    private static readonly pb::MessageParser<ToClient> _parser = new pb::MessageParser<ToClient>(() => new ToClient());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ToClient> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Opencraft.NetCode.OpencraftReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ToClient() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ToClient(ToClient other) : this() {
      switch (other.PayloadCase) {
        case PayloadOneofCase.YouArePlayer:
          YouArePlayer = other.YouArePlayer.Clone();
          break;
        case PayloadOneofCase.PlayerUpdate:
          PlayerUpdate = other.PlayerUpdate.Clone();
          break;
        case PayloadOneofCase.ChunkData:
          ChunkData = other.ChunkData.Clone();
          break;
        case PayloadOneofCase.ColumnData:
          ColumnData = other.ColumnData.Clone();
          break;
        case PayloadOneofCase.BlockUpdate:
          BlockUpdate = other.BlockUpdate.Clone();
          break;
        case PayloadOneofCase.MultiBlockUpdate:
          MultiBlockUpdate = other.MultiBlockUpdate.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ToClient Clone() {
      return new ToClient(this);
    }

    /// <summary>Field number for the "you_are_player" field.</summary>
    public const int YouArePlayerFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Opencraft.NetCode.YouArePlayer YouArePlayer {
      get { return payloadCase_ == PayloadOneofCase.YouArePlayer ? (global::Opencraft.NetCode.YouArePlayer) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.YouArePlayer;
      }
    }

    /// <summary>Field number for the "player_update" field.</summary>
    public const int PlayerUpdateFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Opencraft.NetCode.PlayerUpdate PlayerUpdate {
      get { return payloadCase_ == PayloadOneofCase.PlayerUpdate ? (global::Opencraft.NetCode.PlayerUpdate) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.PlayerUpdate;
      }
    }

    /// <summary>Field number for the "chunk_data" field.</summary>
    public const int ChunkDataFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Opencraft.NetCode.ChunkData ChunkData {
      get { return payloadCase_ == PayloadOneofCase.ChunkData ? (global::Opencraft.NetCode.ChunkData) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.ChunkData;
      }
    }

    /// <summary>Field number for the "column_data" field.</summary>
    public const int ColumnDataFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Opencraft.NetCode.ColumnData ColumnData {
      get { return payloadCase_ == PayloadOneofCase.ColumnData ? (global::Opencraft.NetCode.ColumnData) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.ColumnData;
      }
    }

    /// <summary>Field number for the "block_update" field.</summary>
    public const int BlockUpdateFieldNumber = 5;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Opencraft.NetCode.BlockUpdate BlockUpdate {
      get { return payloadCase_ == PayloadOneofCase.BlockUpdate ? (global::Opencraft.NetCode.BlockUpdate) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.BlockUpdate;
      }
    }

    /// <summary>Field number for the "multi_block_update" field.</summary>
    public const int MultiBlockUpdateFieldNumber = 6;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Opencraft.NetCode.MultiBlockUpdate MultiBlockUpdate {
      get { return payloadCase_ == PayloadOneofCase.MultiBlockUpdate ? (global::Opencraft.NetCode.MultiBlockUpdate) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.MultiBlockUpdate;
      }
    }

    private object payload_;
    /// <summary>Enum of possible cases for the "payload" oneof.</summary>
    public enum PayloadOneofCase {
      None = 0,
      YouArePlayer = 1,
      PlayerUpdate = 2,
      ChunkData = 3,
      ColumnData = 4,
      BlockUpdate = 5,
      MultiBlockUpdate = 6,
    }
    private PayloadOneofCase payloadCase_ = PayloadOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PayloadOneofCase PayloadCase {
      get { return payloadCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearPayload() {
      payloadCase_ = PayloadOneofCase.None;
      payload_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ToClient);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ToClient other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(YouArePlayer, other.YouArePlayer)) return false;
      if (!object.Equals(PlayerUpdate, other.PlayerUpdate)) return false;
      if (!object.Equals(ChunkData, other.ChunkData)) return false;
      if (!object.Equals(ColumnData, other.ColumnData)) return false;
      if (!object.Equals(BlockUpdate, other.BlockUpdate)) return false;
      if (!object.Equals(MultiBlockUpdate, other.MultiBlockUpdate)) return false;
      if (PayloadCase != other.PayloadCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (payloadCase_ == PayloadOneofCase.YouArePlayer) hash ^= YouArePlayer.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.PlayerUpdate) hash ^= PlayerUpdate.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.ChunkData) hash ^= ChunkData.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.ColumnData) hash ^= ColumnData.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.BlockUpdate) hash ^= BlockUpdate.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.MultiBlockUpdate) hash ^= MultiBlockUpdate.GetHashCode();
      hash ^= (int) payloadCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (payloadCase_ == PayloadOneofCase.YouArePlayer) {
        output.WriteRawTag(10);
        output.WriteMessage(YouArePlayer);
      }
      if (payloadCase_ == PayloadOneofCase.PlayerUpdate) {
        output.WriteRawTag(18);
        output.WriteMessage(PlayerUpdate);
      }
      if (payloadCase_ == PayloadOneofCase.ChunkData) {
        output.WriteRawTag(26);
        output.WriteMessage(ChunkData);
      }
      if (payloadCase_ == PayloadOneofCase.ColumnData) {
        output.WriteRawTag(34);
        output.WriteMessage(ColumnData);
      }
      if (payloadCase_ == PayloadOneofCase.BlockUpdate) {
        output.WriteRawTag(42);
        output.WriteMessage(BlockUpdate);
      }
      if (payloadCase_ == PayloadOneofCase.MultiBlockUpdate) {
        output.WriteRawTag(50);
        output.WriteMessage(MultiBlockUpdate);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (payloadCase_ == PayloadOneofCase.YouArePlayer) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(YouArePlayer);
      }
      if (payloadCase_ == PayloadOneofCase.PlayerUpdate) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PlayerUpdate);
      }
      if (payloadCase_ == PayloadOneofCase.ChunkData) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ChunkData);
      }
      if (payloadCase_ == PayloadOneofCase.ColumnData) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ColumnData);
      }
      if (payloadCase_ == PayloadOneofCase.BlockUpdate) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BlockUpdate);
      }
      if (payloadCase_ == PayloadOneofCase.MultiBlockUpdate) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MultiBlockUpdate);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ToClient other) {
      if (other == null) {
        return;
      }
      switch (other.PayloadCase) {
        case PayloadOneofCase.YouArePlayer:
          if (YouArePlayer == null) {
            YouArePlayer = new global::Opencraft.NetCode.YouArePlayer();
          }
          YouArePlayer.MergeFrom(other.YouArePlayer);
          break;
        case PayloadOneofCase.PlayerUpdate:
          if (PlayerUpdate == null) {
            PlayerUpdate = new global::Opencraft.NetCode.PlayerUpdate();
          }
          PlayerUpdate.MergeFrom(other.PlayerUpdate);
          break;
        case PayloadOneofCase.ChunkData:
          if (ChunkData == null) {
            ChunkData = new global::Opencraft.NetCode.ChunkData();
          }
          ChunkData.MergeFrom(other.ChunkData);
          break;
        case PayloadOneofCase.ColumnData:
          if (ColumnData == null) {
            ColumnData = new global::Opencraft.NetCode.ColumnData();
          }
          ColumnData.MergeFrom(other.ColumnData);
          break;
        case PayloadOneofCase.BlockUpdate:
          if (BlockUpdate == null) {
            BlockUpdate = new global::Opencraft.NetCode.BlockUpdate();
          }
          BlockUpdate.MergeFrom(other.BlockUpdate);
          break;
        case PayloadOneofCase.MultiBlockUpdate:
          if (MultiBlockUpdate == null) {
            MultiBlockUpdate = new global::Opencraft.NetCode.MultiBlockUpdate();
          }
          MultiBlockUpdate.MergeFrom(other.MultiBlockUpdate);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::Opencraft.NetCode.YouArePlayer subBuilder = new global::Opencraft.NetCode.YouArePlayer();
            if (payloadCase_ == PayloadOneofCase.YouArePlayer) {
              subBuilder.MergeFrom(YouArePlayer);
            }
            input.ReadMessage(subBuilder);
            YouArePlayer = subBuilder;
            break;
          }
          case 18: {
            global::Opencraft.NetCode.PlayerUpdate subBuilder = new global::Opencraft.NetCode.PlayerUpdate();
            if (payloadCase_ == PayloadOneofCase.PlayerUpdate) {
              subBuilder.MergeFrom(PlayerUpdate);
            }
            input.ReadMessage(subBuilder);
            PlayerUpdate = subBuilder;
            break;
          }
          case 26: {
            global::Opencraft.NetCode.ChunkData subBuilder = new global::Opencraft.NetCode.ChunkData();
            if (payloadCase_ == PayloadOneofCase.ChunkData) {
              subBuilder.MergeFrom(ChunkData);
            }
            input.ReadMessage(subBuilder);
            ChunkData = subBuilder;
            break;
          }
          case 34: {
            global::Opencraft.NetCode.ColumnData subBuilder = new global::Opencraft.NetCode.ColumnData();
            if (payloadCase_ == PayloadOneofCase.ColumnData) {
              subBuilder.MergeFrom(ColumnData);
            }
            input.ReadMessage(subBuilder);
            ColumnData = subBuilder;
            break;
          }
          case 42: {
            global::Opencraft.NetCode.BlockUpdate subBuilder = new global::Opencraft.NetCode.BlockUpdate();
            if (payloadCase_ == PayloadOneofCase.BlockUpdate) {
              subBuilder.MergeFrom(BlockUpdate);
            }
            input.ReadMessage(subBuilder);
            BlockUpdate = subBuilder;
            break;
          }
          case 50: {
            global::Opencraft.NetCode.MultiBlockUpdate subBuilder = new global::Opencraft.NetCode.MultiBlockUpdate();
            if (payloadCase_ == PayloadOneofCase.MultiBlockUpdate) {
              subBuilder.MergeFrom(MultiBlockUpdate);
            }
            input.ReadMessage(subBuilder);
            MultiBlockUpdate = subBuilder;
            break;
          }
        }
      }
    }

  }

  public sealed partial class YouArePlayer : pb::IMessage<YouArePlayer> {
    private static readonly pb::MessageParser<YouArePlayer> _parser = new pb::MessageParser<YouArePlayer>(() => new YouArePlayer());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<YouArePlayer> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Opencraft.NetCode.OpencraftReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public YouArePlayer() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public YouArePlayer(YouArePlayer other) : this() {
      playerID_ = other.playerID_;
      spawnLocation_ = other.spawnLocation_ != null ? other.spawnLocation_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public YouArePlayer Clone() {
      return new YouArePlayer(this);
    }

    /// <summary>Field number for the "playerID" field.</summary>
    public const int PlayerIDFieldNumber = 1;
    private uint playerID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint PlayerID {
      get { return playerID_; }
      set {
        playerID_ = value;
      }
    }

    /// <summary>Field number for the "spawnLocation" field.</summary>
    public const int SpawnLocationFieldNumber = 2;
    private global::Opencraft.NetCode.Vec3 spawnLocation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Opencraft.NetCode.Vec3 SpawnLocation {
      get { return spawnLocation_; }
      set {
        spawnLocation_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as YouArePlayer);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(YouArePlayer other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PlayerID != other.PlayerID) return false;
      if (!object.Equals(SpawnLocation, other.SpawnLocation)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (PlayerID != 0) hash ^= PlayerID.GetHashCode();
      if (spawnLocation_ != null) hash ^= SpawnLocation.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (PlayerID != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(PlayerID);
      }
      if (spawnLocation_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(SpawnLocation);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (PlayerID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PlayerID);
      }
      if (spawnLocation_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SpawnLocation);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(YouArePlayer other) {
      if (other == null) {
        return;
      }
      if (other.PlayerID != 0) {
        PlayerID = other.PlayerID;
      }
      if (other.spawnLocation_ != null) {
        if (spawnLocation_ == null) {
          SpawnLocation = new global::Opencraft.NetCode.Vec3();
        }
        SpawnLocation.MergeFrom(other.SpawnLocation);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            PlayerID = input.ReadUInt32();
            break;
          }
          case 18: {
            if (spawnLocation_ == null) {
              SpawnLocation = new global::Opencraft.NetCode.Vec3();
            }
            input.ReadMessage(SpawnLocation);
            break;
          }
        }
      }
    }

  }

  public sealed partial class Vec3 : pb::IMessage<Vec3> {
    private static readonly pb::MessageParser<Vec3> _parser = new pb::MessageParser<Vec3>(() => new Vec3());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Vec3> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Opencraft.NetCode.OpencraftReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Vec3() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Vec3(Vec3 other) : this() {
      x_ = other.x_;
      y_ = other.y_;
      z_ = other.z_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Vec3 Clone() {
      return new Vec3(this);
    }

    /// <summary>Field number for the "x" field.</summary>
    public const int XFieldNumber = 1;
    private float x_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float X {
      get { return x_; }
      set {
        x_ = value;
      }
    }

    /// <summary>Field number for the "y" field.</summary>
    public const int YFieldNumber = 2;
    private float y_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Y {
      get { return y_; }
      set {
        y_ = value;
      }
    }

    /// <summary>Field number for the "z" field.</summary>
    public const int ZFieldNumber = 3;
    private float z_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Z {
      get { return z_; }
      set {
        z_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Vec3);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Vec3 other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(X, other.X)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Y, other.Y)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Z, other.Z)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (X != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(X);
      if (Y != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Y);
      if (Z != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Z);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (X != 0F) {
        output.WriteRawTag(13);
        output.WriteFloat(X);
      }
      if (Y != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(Y);
      }
      if (Z != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(Z);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (X != 0F) {
        size += 1 + 4;
      }
      if (Y != 0F) {
        size += 1 + 4;
      }
      if (Z != 0F) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Vec3 other) {
      if (other == null) {
        return;
      }
      if (other.X != 0F) {
        X = other.X;
      }
      if (other.Y != 0F) {
        Y = other.Y;
      }
      if (other.Z != 0F) {
        Z = other.Z;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 13: {
            X = input.ReadFloat();
            break;
          }
          case 21: {
            Y = input.ReadFloat();
            break;
          }
          case 29: {
            Z = input.ReadFloat();
            break;
          }
        }
      }
    }

  }

  public sealed partial class Pos2 : pb::IMessage<Pos2> {
    private static readonly pb::MessageParser<Pos2> _parser = new pb::MessageParser<Pos2>(() => new Pos2());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Pos2> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Opencraft.NetCode.OpencraftReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Pos2() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Pos2(Pos2 other) : this() {
      x_ = other.x_;
      z_ = other.z_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Pos2 Clone() {
      return new Pos2(this);
    }

    /// <summary>Field number for the "x" field.</summary>
    public const int XFieldNumber = 1;
    private int x_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int X {
      get { return x_; }
      set {
        x_ = value;
      }
    }

    /// <summary>Field number for the "z" field.</summary>
    public const int ZFieldNumber = 2;
    private int z_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Z {
      get { return z_; }
      set {
        z_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Pos2);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Pos2 other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (X != other.X) return false;
      if (Z != other.Z) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (X != 0) hash ^= X.GetHashCode();
      if (Z != 0) hash ^= Z.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (X != 0) {
        output.WriteRawTag(8);
        output.WriteSInt32(X);
      }
      if (Z != 0) {
        output.WriteRawTag(16);
        output.WriteSInt32(Z);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (X != 0) {
        size += 1 + pb::CodedOutputStream.ComputeSInt32Size(X);
      }
      if (Z != 0) {
        size += 1 + pb::CodedOutputStream.ComputeSInt32Size(Z);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Pos2 other) {
      if (other == null) {
        return;
      }
      if (other.X != 0) {
        X = other.X;
      }
      if (other.Z != 0) {
        Z = other.Z;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            X = input.ReadSInt32();
            break;
          }
          case 16: {
            Z = input.ReadSInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class Pos3 : pb::IMessage<Pos3> {
    private static readonly pb::MessageParser<Pos3> _parser = new pb::MessageParser<Pos3>(() => new Pos3());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Pos3> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Opencraft.NetCode.OpencraftReflection.Descriptor.MessageTypes[9]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Pos3() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Pos3(Pos3 other) : this() {
      x_ = other.x_;
      y_ = other.y_;
      z_ = other.z_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Pos3 Clone() {
      return new Pos3(this);
    }

    /// <summary>Field number for the "x" field.</summary>
    public const int XFieldNumber = 1;
    private int x_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int X {
      get { return x_; }
      set {
        x_ = value;
      }
    }

    /// <summary>Field number for the "y" field.</summary>
    public const int YFieldNumber = 2;
    private int y_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Y {
      get { return y_; }
      set {
        y_ = value;
      }
    }

    /// <summary>Field number for the "z" field.</summary>
    public const int ZFieldNumber = 3;
    private int z_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Z {
      get { return z_; }
      set {
        z_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Pos3);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Pos3 other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (X != other.X) return false;
      if (Y != other.Y) return false;
      if (Z != other.Z) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (X != 0) hash ^= X.GetHashCode();
      if (Y != 0) hash ^= Y.GetHashCode();
      if (Z != 0) hash ^= Z.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (X != 0) {
        output.WriteRawTag(8);
        output.WriteSInt32(X);
      }
      if (Y != 0) {
        output.WriteRawTag(16);
        output.WriteSInt32(Y);
      }
      if (Z != 0) {
        output.WriteRawTag(24);
        output.WriteSInt32(Z);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (X != 0) {
        size += 1 + pb::CodedOutputStream.ComputeSInt32Size(X);
      }
      if (Y != 0) {
        size += 1 + pb::CodedOutputStream.ComputeSInt32Size(Y);
      }
      if (Z != 0) {
        size += 1 + pb::CodedOutputStream.ComputeSInt32Size(Z);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Pos3 other) {
      if (other == null) {
        return;
      }
      if (other.X != 0) {
        X = other.X;
      }
      if (other.Y != 0) {
        Y = other.Y;
      }
      if (other.Z != 0) {
        Z = other.Z;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            X = input.ReadSInt32();
            break;
          }
          case 16: {
            Y = input.ReadSInt32();
            break;
          }
          case 24: {
            Z = input.ReadSInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class PlayerUpdate : pb::IMessage<PlayerUpdate> {
    private static readonly pb::MessageParser<PlayerUpdate> _parser = new pb::MessageParser<PlayerUpdate>(() => new PlayerUpdate());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PlayerUpdate> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Opencraft.NetCode.OpencraftReflection.Descriptor.MessageTypes[10]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlayerUpdate() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlayerUpdate(PlayerUpdate other) : this() {
      playerID_ = other.playerID_;
      position_ = other.position_ != null ? other.position_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PlayerUpdate Clone() {
      return new PlayerUpdate(this);
    }

    /// <summary>Field number for the "playerID" field.</summary>
    public const int PlayerIDFieldNumber = 1;
    private uint playerID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint PlayerID {
      get { return playerID_; }
      set {
        playerID_ = value;
      }
    }

    /// <summary>Field number for the "position" field.</summary>
    public const int PositionFieldNumber = 2;
    private global::Opencraft.NetCode.Vec3 position_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Opencraft.NetCode.Vec3 Position {
      get { return position_; }
      set {
        position_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PlayerUpdate);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PlayerUpdate other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PlayerID != other.PlayerID) return false;
      if (!object.Equals(Position, other.Position)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (PlayerID != 0) hash ^= PlayerID.GetHashCode();
      if (position_ != null) hash ^= Position.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (PlayerID != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(PlayerID);
      }
      if (position_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Position);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (PlayerID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PlayerID);
      }
      if (position_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Position);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PlayerUpdate other) {
      if (other == null) {
        return;
      }
      if (other.PlayerID != 0) {
        PlayerID = other.PlayerID;
      }
      if (other.position_ != null) {
        if (position_ == null) {
          Position = new global::Opencraft.NetCode.Vec3();
        }
        Position.MergeFrom(other.Position);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            PlayerID = input.ReadUInt32();
            break;
          }
          case 18: {
            if (position_ == null) {
              Position = new global::Opencraft.NetCode.Vec3();
            }
            input.ReadMessage(Position);
            break;
          }
        }
      }
    }

  }

  public sealed partial class ChunkData : pb::IMessage<ChunkData> {
    private static readonly pb::MessageParser<ChunkData> _parser = new pb::MessageParser<ChunkData>(() => new ChunkData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ChunkData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Opencraft.NetCode.OpencraftReflection.Descriptor.MessageTypes[11]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ChunkData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ChunkData(ChunkData other) : this() {
      blockTypes_ = other.blockTypes_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ChunkData Clone() {
      return new ChunkData(this);
    }

    /// <summary>Field number for the "blockTypes" field.</summary>
    public const int BlockTypesFieldNumber = 1;
    private pb::ByteString blockTypes_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString BlockTypes {
      get { return blockTypes_; }
      set {
        blockTypes_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ChunkData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ChunkData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (BlockTypes != other.BlockTypes) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (BlockTypes.Length != 0) hash ^= BlockTypes.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (BlockTypes.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(BlockTypes);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (BlockTypes.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(BlockTypes);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ChunkData other) {
      if (other == null) {
        return;
      }
      if (other.BlockTypes.Length != 0) {
        BlockTypes = other.BlockTypes;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            BlockTypes = input.ReadBytes();
            break;
          }
        }
      }
    }

  }

  public sealed partial class ColumnData : pb::IMessage<ColumnData> {
    private static readonly pb::MessageParser<ColumnData> _parser = new pb::MessageParser<ColumnData>(() => new ColumnData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ColumnData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Opencraft.NetCode.OpencraftReflection.Descriptor.MessageTypes[12]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ColumnData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ColumnData(ColumnData other) : this() {
      position_ = other.position_ != null ? other.position_.Clone() : null;
      chunks_ = other.chunks_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ColumnData Clone() {
      return new ColumnData(this);
    }

    /// <summary>Field number for the "position" field.</summary>
    public const int PositionFieldNumber = 1;
    private global::Opencraft.NetCode.Pos2 position_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Opencraft.NetCode.Pos2 Position {
      get { return position_; }
      set {
        position_ = value;
      }
    }

    /// <summary>Field number for the "chunks" field.</summary>
    public const int ChunksFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Opencraft.NetCode.ChunkData> _repeated_chunks_codec
        = pb::FieldCodec.ForMessage(18, global::Opencraft.NetCode.ChunkData.Parser);
    private readonly pbc::RepeatedField<global::Opencraft.NetCode.ChunkData> chunks_ = new pbc::RepeatedField<global::Opencraft.NetCode.ChunkData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Opencraft.NetCode.ChunkData> Chunks {
      get { return chunks_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ColumnData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ColumnData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Position, other.Position)) return false;
      if(!chunks_.Equals(other.chunks_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (position_ != null) hash ^= Position.GetHashCode();
      hash ^= chunks_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (position_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Position);
      }
      chunks_.WriteTo(output, _repeated_chunks_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (position_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Position);
      }
      size += chunks_.CalculateSize(_repeated_chunks_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ColumnData other) {
      if (other == null) {
        return;
      }
      if (other.position_ != null) {
        if (position_ == null) {
          Position = new global::Opencraft.NetCode.Pos2();
        }
        Position.MergeFrom(other.Position);
      }
      chunks_.Add(other.chunks_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (position_ == null) {
              Position = new global::Opencraft.NetCode.Pos2();
            }
            input.ReadMessage(Position);
            break;
          }
          case 18: {
            chunks_.AddEntriesFrom(input, _repeated_chunks_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class BlockUpdate : pb::IMessage<BlockUpdate> {
    private static readonly pb::MessageParser<BlockUpdate> _parser = new pb::MessageParser<BlockUpdate>(() => new BlockUpdate());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<BlockUpdate> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Opencraft.NetCode.OpencraftReflection.Descriptor.MessageTypes[13]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BlockUpdate() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BlockUpdate(BlockUpdate other) : this() {
      blockPosition_ = other.blockPosition_ != null ? other.blockPosition_.Clone() : null;
      blockType_ = other.blockType_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BlockUpdate Clone() {
      return new BlockUpdate(this);
    }

    /// <summary>Field number for the "blockPosition" field.</summary>
    public const int BlockPositionFieldNumber = 1;
    private global::Opencraft.NetCode.Pos3 blockPosition_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Opencraft.NetCode.Pos3 BlockPosition {
      get { return blockPosition_; }
      set {
        blockPosition_ = value;
      }
    }

    /// <summary>Field number for the "blockType" field.</summary>
    public const int BlockTypeFieldNumber = 2;
    private uint blockType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint BlockType {
      get { return blockType_; }
      set {
        blockType_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as BlockUpdate);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(BlockUpdate other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(BlockPosition, other.BlockPosition)) return false;
      if (BlockType != other.BlockType) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (blockPosition_ != null) hash ^= BlockPosition.GetHashCode();
      if (BlockType != 0) hash ^= BlockType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (blockPosition_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(BlockPosition);
      }
      if (BlockType != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(BlockType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (blockPosition_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BlockPosition);
      }
      if (BlockType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(BlockType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(BlockUpdate other) {
      if (other == null) {
        return;
      }
      if (other.blockPosition_ != null) {
        if (blockPosition_ == null) {
          BlockPosition = new global::Opencraft.NetCode.Pos3();
        }
        BlockPosition.MergeFrom(other.BlockPosition);
      }
      if (other.BlockType != 0) {
        BlockType = other.BlockType;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (blockPosition_ == null) {
              BlockPosition = new global::Opencraft.NetCode.Pos3();
            }
            input.ReadMessage(BlockPosition);
            break;
          }
          case 16: {
            BlockType = input.ReadUInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class MultiBlockUpdate : pb::IMessage<MultiBlockUpdate> {
    private static readonly pb::MessageParser<MultiBlockUpdate> _parser = new pb::MessageParser<MultiBlockUpdate>(() => new MultiBlockUpdate());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MultiBlockUpdate> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Opencraft.NetCode.OpencraftReflection.Descriptor.MessageTypes[14]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MultiBlockUpdate() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MultiBlockUpdate(MultiBlockUpdate other) : this() {
      updates_ = other.updates_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MultiBlockUpdate Clone() {
      return new MultiBlockUpdate(this);
    }

    /// <summary>Field number for the "updates" field.</summary>
    public const int UpdatesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Opencraft.NetCode.BlockUpdate> _repeated_updates_codec
        = pb::FieldCodec.ForMessage(10, global::Opencraft.NetCode.BlockUpdate.Parser);
    private readonly pbc::RepeatedField<global::Opencraft.NetCode.BlockUpdate> updates_ = new pbc::RepeatedField<global::Opencraft.NetCode.BlockUpdate>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Opencraft.NetCode.BlockUpdate> Updates {
      get { return updates_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MultiBlockUpdate);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MultiBlockUpdate other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!updates_.Equals(other.updates_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= updates_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      updates_.WriteTo(output, _repeated_updates_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += updates_.CalculateSize(_repeated_updates_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MultiBlockUpdate other) {
      if (other == null) {
        return;
      }
      updates_.Add(other.updates_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            updates_.AddEntriesFrom(input, _repeated_updates_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
